package com.example.demo.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.example.demo.util.DynamoDBLocalDateTimeConverter;
import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@DynamoDBTable(tableName = "OVERRIDDEN_AT_RUNTIME")
@JsonInclude(JsonInclude.Include.NON_NULL)
@Data
@NoArgsConstructor
public class User {

    public static final String TABLE_NAME = System.getenv("USER_TABLE_NAME");

    public static final String EMAIL_INDEX = "email-index";

    // attribute name
    public static final String ID_NAME = "id";
    public static final String EMAIL_NAME = "email";
    public static final String CREATED_NAME = "created";
    public static final String LAST_MODIFIED_NAME = "lastModified";
    public static final String PASSWORD_NAME = "password";

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = DynamoDBLocalDateTimeConverter.class)
    private LocalDateTime created;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = DynamoDBLocalDateTimeConverter.class)
    private LocalDateTime lastModified;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = EMAIL_INDEX)
    private String email;

    private String password;

}
